/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import multiSelect from "strapi-plugin-multi-select/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "multi-select": multiSelect,
  },
});
